title: Deuts Docs
description: The home of Deuts documents
theme: just-the-docs

url: https://deuts.github.io/wiki

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

nav_enabled: true
color_scheme: dark
