title: Deuts Docs
description: The home of Deuts documents
theme: just-the-docs
color_scheme: dark
permalink: pretty
favicon_ico: "/assets/images/wiki.ico"

nav_enabled: true

url: https://deuts.github.io/wiki

## Aux Links (upper right links)
aux_links:
  Blog: https://deuts.org
  About: https://deuts.org/i/about/
  Contact: https://deuts.org/i/contact/
aux_links_new_tab: true

# Search
search_enabled: true

collections:
  docker:
    output: true
#  tutorials:
#    output: true

just_the_docs:
  collections:
    docker:
      name: Docker Apps
      nav_fold: true
#    tutorials:
#      name: Tutorials
#      nav_fold: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default