title: Deuts Docs
description: The home of Deuts documents
theme: just-the-docs

url: https://deuts.github.io/wiki

aux_links:
  Blog: https://deuts.org
  About: https://deuts.org/i/about/
  Contact: https://deuts.org/i/contact/

nav_enabled: true
color_scheme: dark

# Search
search_enabled: true
search: 
  button: true