title: Deuts Wiki
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://deuts.github.io/wiki

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

nav_enabled: true
color_scheme: dark
